### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by lenborje** [dwagelaar/jar2uml#2]
Just installed 1.2.0 from the MarketPlace into my Oxygen.2 (4.7.2). Tried to "Import Java Project". Whatever I try, the result is just a NullPointerException. Cf. attached screenshot.

![skarmavbild 2018-03-06 kl 14 50 05](https://user-images.githubusercontent.com/11754011/37035835-0f80560c-214e-11e8-8ff9-91bd1715d58e.png)

**Comment by dwagelaar** [comment]
Can you post the stack trace as well? It can be found in the Error Log view:

- Click "Window -> Show View -> Other"
- Select "General -> Error Log" and click "Open"
- Double-click the line with "java.lang.NullPointerException"

**Comment by lenborje** [comment]
eclipse.buildId=4.7.2.M20171130-0510
java.version=9.0.4
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=sv_SE
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -keyring /Users/lennartb/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -data file:/Users/lennartb/Documents/eclipseBMF/ -product org.eclipse.epp.package.java.product -keyring /Users/lennartb/.eclipse_keyring

org.eclipselabs.jar2uml
Error
Tue Mar 06 14:03:13 CET 2018
java.lang.NullPointerException

java.lang.NullPointerException
	at org.eclipselabs.jar2uml.ParseClasses.findClassFilesIn(ParseClasses.java:64)
	at org.eclipselabs.jar2uml.ParseClasses.findClassFilesIn(ParseClasses.java:70)
	at org.eclipselabs.jar2uml.ParseClasses.findClassFilesIn(ParseClasses.java:70)
	at org.eclipselabs.jar2uml.ParseClasses.getPathWork(ParseClasses.java:96)
	at org.eclipselabs.jar2uml.JarToUML.runWithMonitor(JarToUML.java:334)
	at org.eclipselabs.jar2uml.JarToUMLRunnable.run(JarToUMLRunnable.java:39)
	at org.eclipselabs.jar2uml.ui.AbstractImportWizardPage.createFile(AbstractImportWizardPage.java:257)
	at org.eclipselabs.jar2uml.ui.AbstractImportWizardPage$2.runInWorkspace(AbstractImportWizardPage.java:188)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by dwagelaar** [comment]
Included in release 2.0.0.
